CONTIKI_PROJECT = border_node
all: $(CONTIKI_PROJECT)

# Add library of sensor
CONTIKI_TARGET_SOURCEFILES += dht22.c
PROJECT_SOURCEFILES += ../network_configuration.c

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include


