#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

//NETWORK CONFIGURATION
#define IEEE802154_CONF_PANID 0x78f5
#define IEEE802154_CONF_DEFAULT_CHANNEL 5

#define ENERGEST_CONF_ON 1
#define QUEUEBUF_CONF_NUM  4

#endif /* PROJECT_CONF_H_ */